"""add enums and role column

Revision ID: 5eb9d4abd8fa
Revises: 6f1eaffe97c0
Create Date: 2026-06-27 10:58:24.287853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb9d4abd8fa'
down_revision: Union[str, Sequence[str], None] = '6f1eaffe97c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types first
    userrole = sa.Enum('CUSTOMER', 'MERCHANT', name='userrole')
    paymentstatus = sa.Enum('INITIATED', 'VALIDATING', 'PROCESSING', 'SUCCESS', 'REJECTED', 'FAILED', 'ROLLED_BACK',
                            name='paymentstatus')

    userrole.create(op.get_bind())
    paymentstatus.create(op.get_bind())

    op.add_column('customers', sa.Column('role', userrole, nullable=False, server_default='CUSTOMER'))
    op.add_column('merchants', sa.Column('role', userrole, nullable=False, server_default='MERCHANT'))
    op.alter_column('payments', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=paymentstatus,
                    nullable=False,
                    postgresql_using='status::paymentstatus')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('INITIATED', 'VALIDATING', 'PROCESSING', 'SUCCESS', 'REJECTED', 'FAILED', 'ROLLED_BACK', name='paymentstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('merchants', 'role')
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
